### ISSUE TITLE
Character encoding issue

### ISSUE THREAD

**Issue by vijoc** [jyrkioraskari/IFCtoLBD#10]
There seems to be an issue in the character decoding/encoding of the conversion. When converting a space with the name `Käytävä`, the output for the related `opm:CurrentState` is

    schema:value          "K\\X\\E4yt\\X\\E4v\\X\\E4"

A likely candidate for this behavior is in the [writeModel](https://github.com/jyrkioraskari/IFCtoLBD/blob/58ee925553373c35c357464e87066dfdd180d7cd/converter/src/main/java/org/lbd/ifc2lbd/IFCtoLBDConverter.java#L363) function. Assuming the problem is in the output encoding, wrapping the `FileOutputStream` in an `OutputStreamWriter` with an explicit UTF-8 encoding should fix it.

**Comment by jyrkioraskari** [comment]
Hi,  thank you.  I apologize for the late response. This is fixed in version 2.7.
Your solution was a good start. The actual error happens earlier in process in the Apache Jena StreamRDFWriter implementation that is used by IFCtoRDF. My Java code did not understand the outputted data although it was UTF-encoded. The output had to be UTF-8 decoded first and then written back as UTF-8.  I tested it and the solution seems to be fine, 

Hei, kiitos palautteesta. Olen pahoillani että kesti. Tämä on korjattu versiossa 2.7.
Esittämäsi ratkaisu oli periaattessa oikein, mutta Java koodini ei tunnistanut Apache Jena StreamRDFWriter:n tuottamaa koodausta ja siten piti ensin UTF-8 dekoodata ennen uudelleenkirjoittamista UTF-8:na. Testasin ratkaisun ja näyttäisi olevan kunnossa
